// Generated by CoffeeScript 2.3.1
(function() {
  Template.GraphButtons.rendered = function() {
    return $(".graph-debug").click(function() {
      debugger;
    });
  };

  Template.GraphButtons.helpers({
    graphSelected: function() {
      return (Session.get('graphName')) !== null;
    },
    bluemix: function() {
      return (Session.get('serverURL')) === window.BluemixGraphService;
    }
  });

}).call(this);

//# sourceMappingURL=GraphButtons.js.map
