// Generated by CoffeeScript 2.3.1
(function() {
  Template.Help.rendered = function() {
    $(".goto-gitlab").click(function() {
      return open(Session.get('gitLabURL'));
    });
    return $(".goto-gitlab-issues").click(function() {
      return open(Session.get('gitLabIssuesURL'));
    });
  };

  //comment

}).call(this);

//# sourceMappingURL=Help.js.map
