// Generated by CoffeeScript 2.3.1
(function() {
  var defaultScript, escapeDollarSignInStrings, scriptCode, scriptURLForStandalone, stripComments;

  defaultScript = 'Select a script from above or add a named script first using the [+Add] button.';

  Template.ScriptOrganizerSelectorAndEditor.rendered = function() {
    Tracker.autorun(function(e) {
      window.ScriptEditor = AceEditor.instance('scriptEditor');
      if (window.ScriptEditor.loaded === true) {
        e.stop();
        window.ScriptEditor.insert(defaultScript);
        Session.set('scriptCode', '');
        // window.ScriptEditor.setTheme('ace/theme/github')
        window.ScriptEditor.getSession().setMode('ace/mode/groovy');
        window.ScriptEditor.getSession().setUseWrapMode(true);
        return window.ScriptEditor.getSession().setWrapLimitRange();
      }
    });
    $("#scriptSelector").change(function() {
      var scriptName;
      scriptName = $("#scriptSelector").val();
      Session.set('scriptName', scriptName);
      Session.set('scriptResult', null);
      Session.set('queryTime', 'N/A');
      Session.set('elapsedTime', 'N/A');
      Session.set('runStatus', 'Ready');
      Session.set('graphFoundInResults', false);
      Session.set('graphRenderingStatus', 'Run script first');
      Session.set('drawButtonPressed', false);
      Session.set('renderStartTime', null);
      Session.set('scriptCode', scriptCode());
      window.ScriptEditor.setValue(Session.get('scriptCode'));
      if (window.resultsEditor) {
        return window.resultsEditor.set({});
      }
    });
    return $(".script-url-test").click(function() {
      return open(scriptURLForStandalone());
    });
  };

  //------------------ Utility functions  ----------------------
  scriptCode = function() {
    var graphName, record, scriptName, serverURL, userID;
    userID = Session.get('userID');
    serverURL = Session.get('serverURL');
    graphName = Session.get('graphName');
    scriptName = Session.get('scriptName');
    if (userID && serverURL && graphName && scriptName) {
      record = Scripts.findOne({
        userID: userID,
        serverURL: serverURL,
        graphName: graphName,
        scriptName: scriptName
      });
      if (!record) {
        record = Scripts.findOne({
          userID: Session.get('examples-userID'),
          serverURL: serverURL,
          graphName: graphName,
          scriptName: scriptName
        });
      }
      Session.set('scriptCode', record.scriptCode);
      Session.set('scriptResult', null);
      //window.resultsEditor.set {}
      return record.scriptCode;
    } else {
      return '';
    }
  };

  stripComments = function(script) {
    var stripped;
    stripped = script.replace(/(?:\/\*(?:[\s\S]*?)\*\/)|(?:([\s;])+\/\/(?:.*)$)/gm, ''); //strip comments of all kinds
    //stripped = stripped.replace(/\t+/g,' ')  #replace tabs with spaces
    return stripped;
  };

  escapeDollarSignInStrings = function(script) {
    return script.replace(/\$/g, '\\$'); //escape $ with \$ due to Java string insertion matcher
  };

  scriptURLForStandalone = function() {
    var url;
    if ((Session.get('tinkerPopVersion')) === '2') {
      url = (Session.get('serverURL')) + '/graphs/' + (Session.get('graphName')) + '/tp/gremlin?script=' + encodeURIComponent(escapeDollarSignInStrings(stripComments(scriptCode())));
    }
    if ((Session.get('tinkerPopVersion')) === '3') {
      url = (Session.get('serverURL')) + '/?gremlin=' + encodeURIComponent(escapeDollarSignInStrings(stripComments(scriptCode())));
    }
    return url;
  };

  //------------------ Button definitions -----------------------
  Template.ScriptOrganizerSelectorAndEditor.helpers({
    bookNames: function() {
      var all, allFor, each, foo, serverURL, sorted, userID;
      userID = Session.get('userID');
      serverURL = Session.get('serverURL');
      foo = Session.get('bookName');
      if (userID && serverURL) {
        allFor = Books.find({
          userID: userID,
          serverURL: serverURL
        }).fetch();
        all = (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = allFor.length; i < len; i++) {
            each = allFor[i];
            results.push(each.bookName);
          }
          return results;
        })();
        sorted = _.sortBy(all, function(e) {
          return e.toLocaleLowerCase();
        });
        return sorted;
      } else {
        return [];
      }
    },
    bookName: function() {
      return this;
    },
    recipeName: function() {
      return this;
    },
    scriptName: function() {
      return this;
    },
    graphSelected: function() {
      return (Session.get('graphName')) !== null;
    },
    scriptSelected: function() {
      return (Session.get('scriptName')) !== null;
    },
    scriptURL: function() {
      return scriptURLForStandalone();
    },
    notBluemix: function() {
      (Session.get('serverURL')) !== window.BluemixGraphService;
      return false;
    },
    tinkerPopVersion: function() {
      return Session.get('tinkerPopVersion');
    }
  });

}).call(this);

//# sourceMappingURL=ScriptOrganizerSelectorAndEditor.js.map
