// Generated by CoffeeScript 2.3.1
(function() {
  Template.Tools.rendered = function() {};

  Template.Tools.helpers({
    versionNumber: function() {
      return Session.get('versionNumber');
    }
  });

}).call(this);

//# sourceMappingURL=Tools.js.map
