// Generated by CoffeeScript 2.3.1
(function() {
  Template.UserPill.helpers({
    labelClass: function() {
      if (this.status.idle) {
        return "label-warning";
      } else if (this.status.online) {
        return "label-success";
      } else {
        return "label-default";
      }
    }
  });

}).call(this);

//# sourceMappingURL=UserPill.js.map
