// Generated by CoffeeScript 2.3.1
(function() {
  Template.VisitSelector.rendered = function() {
    $(".visitVert").prop('checked', false);
    $(".visitVert").change(function() {
      var checked, id2Visit, label2Visit, verts2Visit, visitCount;
      checked = $(this).prop('checked');
      label2Visit = this.id;
      id2Visit = label2Visit.replace(/[^0-9a-zA-Z]/g, '');
      visitCount = JSON.parse($('input#' + id2Visit + '.visitVertCount').val());
      verts2Visit = Session.get('verts2Visit');
      verts2Visit[label2Visit] = visitCount;
      if (!checked) {
        delete verts2Visit[label2Visit];
      }
      return Session.set('verts2Visit', verts2Visit);
    });
    return $(".visitVertCount").bind('input', function() {
      var id2Count, label2Count, labelChecked, verts2Visit;
      label2Count = this.id;
      id2Count = label2Count.replace(/[^0-9a-zA-Z]/g, '');
      verts2Visit = Session.get('verts2Visit');
      labelChecked = $('input#' + id2Count + '.visitVert.vis-options-checkbox').prop('checked');
      if (labelChecked) {
        verts2Visit[label2Count] = JSON.parse(this.value);
        return Session.set('verts2Visit', verts2Visit);
      }
    });
  };

  Template.VisitSelector.helpers({
    options: function() {
      var i, label, labels, len, ref, tot, vert;
      labels = {};
      ref = this.allV;
      for (i = 0, len = ref.length; i < len; i++) {
        vert = ref[i];
        if (window.UsingGraphSON3) {
          label = vert['@value'].label;
        } else {
          label = vert.label;
        }
        if (labels[label] !== void 0) {
          tot = labels[label];
        } else {
          tot = 0;
        }
        labels[label] = tot + 1;
      }
      Session.set('verts2Visit', {});
      return _.pairs(labels);
    },
    labelID: function() {
      return this[0].replace(/[^0-9a-zA-Z]/g, '');
    },
    label: function() {
      return this[0];
    },
    count: function() {
      return this[1];
    }
  });

}).call(this);

//# sourceMappingURL=VisitSelector.js.map
